### ISSUE TITLE
Clang/MacOS compiler error in opc-ua com layer

### ISSUE THREAD

**Issue by jwalt** [eclipse-4diac/4diac-forte#258] opened 2024-10-07 11:32 UTC
Clang on MacOS (via 4diac-fbe develop branch) fails in the OPC-UA layer:

```
In file included from /home/jwalter/lcl/4diac-fbe/build/test-macos/forte/build/com/opc_ua/opcua_types.cpp:12:
/home/jwalter/lcl/4diac-fbe/forte/src/com/opc_ua/opcua_helper.h:86:40: error: implicit instantiation of undefined template 'std::vector<const UA_Variant *>'
   86 |         std::vector<const UA_Variant*> mData;
      |                                        ^
/home/jwalter/lcl/4diac-fbe/toolchains/clang-toolchain/SDK/MacOSX11.1.sdk/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
  216 | class _LIBCPP_TEMPLATE_VIS vector;
      |                            ^
In file included from /home/jwalter/lcl/4diac-fbe/build/test-macos/forte/build/com/opc_ua/opcua_types.cpp:12:
/home/jwalter/lcl/4diac-fbe/forte/src/com/opc_ua/opcua_helper.h:100:34: error: implicit instantiation of undefined template 'std::vector<UA_Variant *>'
  100 |         std::vector<UA_Variant*> mData;
      |                                  ^
/home/jwalter/lcl/4diac-fbe/toolchains/clang-toolchain/SDK/MacOSX11.1.sdk/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
  216 | class _LIBCPP_TEMPLATE_VIS vector;
```

**Comment by azoitl** [comment] 2024-10-07 14:01
@cochicde could youplease have a look on that.

**Comment by jwalt** [comment] 2024-10-07 15:07
Just as an additional data point: It works fine when using clang for a Linux target. Must be something MacOS specific.

**Comment by cochicde** [comment] 2024-10-07 17:17
I cannot reproduce it locally, but could it be that we are missing a

`#include <vector>`

In that file?

**Comment by jwalt** [comment] 2024-10-07 17:19
You should be able to reproduce with:

```
git clone --recursive -b develop https://github.com/jwalt/4diac-fbe
# download https://github.com/joseluisq/macosx-sdks/releases/tag/11.1 and put it into toolchains subfolder
cd 4diac-fbe
./scripts/compile.sh -v test/test-macos
```
 (the `-v` flag disables parallel builds but improves error reporting)

**Comment by cochicde** [comment] 2024-10-07 18:40
Thanks. I was able to reproduce and test the fix. See #259

**Comment by cochicde** [comment] 2024-10-08 18:49
closing as #259 was merged and fixes the issue

**Closed as completed by cochicde** 2024-10-08 18:49 UTC
